### ISSUE TITLE
Fix 500 error on deployed client

### ISSUE THREAD

**Issue by JordanDickow** [JordanDickow/pokedex-project-2#2]

**Comment by JordanDickow** [comment]
```
status=500

Started POST "//sign-up" for 144.121.82.194 at 2019-06-14 20:06:52 +0000
2019-06-14T20:06:52.698334+00:00 app[web.1]: [397222ce-3c78-4001-ba04-8dc874bffcdb] Processing by UsersController#signup as */*
2019-06-14T20:06:52.698492+00:00 app[web.1]: [397222ce-3c78-4001-ba04-8dc874bffcdb]   Parameters: {"credentials"=>{"email"=>"123@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}
2019-06-14T20:06:52.843265+00:00 app[web.1]: [397222ce-3c78-4001-ba04-8dc874bffcdb] Completed 500 Internal Server Error in 144ms (ActiveRecord: 98.1ms)
2019-06-14T20:06:52.844130+00:00 app[web.1]: [397222ce-3c78-4001-ba04-8dc874bffcdb]
2019-06-14T20:06:52.844193+00:00 app[web.1]: [397222ce-3c78-4001-ba04-8dc874bffcdb] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
2019-06-14T20:06:52.844197+00:00 app[web.1]: LINE 8:                WHERE a.attrelid = '"users"'::regclass
2019-06-14T20:06:52.844200+00:00 app[web.1]: ^
2019-06-14T20:06:52.844203+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2019-06-14T20:06:52.844205+00:00 app[web.1]: pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
2019-06-14T20:06:52.844207+00:00 app[web.1]: c.collname, col_description(a.attrelid, a.attnum) AS comment
2019-06-14T20:06:52.844209+00:00 app[web.1]: FROM pg_attribute a
2019-06-14T20:06:52.844211+00:00 app[web.1]: LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2019-06-14T20:06:52.844213+00:00 app[web.1]: LEFT JOIN pg_type t ON a.atttypid = t.oid
2019-06-14T20:06:52.844216+00:00 app[web.1]: LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
2019-06-14T20:06:52.844218+00:00 app[web.1]: WHERE a.attrelid = '"users"'::regclass
2019-06-14T20:06:52.844219+00:00 app[web.1]: AND a.attnum > 0 AND NOT a.attisdropped
2019-06-14T20:06:52.844221+00:00 app[web.1]: ORDER BY a.attnum
2019-06-14T20:06:52.844224+00:00 app[web.1]: ):
2019-06-14T20:06:52.844230+00:00 app[web.1]: [397222ce-3c78-4001-ba04-8dc874bffcdb]
2019-06-14T20:06:52.844280+00:00 app[web.1]: [397222ce-3c78-4001-ba04-8dc874bffcdb] app/controllers/users_controller.rb:8:in `signup'
2019-06-14T20:06:52.849927+00:00 heroku[router]: at=info method=POST path="//sign-up" host=enigmatic-retreat-33385.herokuapp.com request_id=397222ce-3c78-4001-ba04-8dc874bffcdb fwd="144.121.82.194" dyno=web.1 connect=0ms service=166ms status=500 bytes=460 protocol=https
```

**Comment by JordanDickow** [comment]
Here are most identifable errors
ActiveRecord::StatementInvalid (PG::UndefinedTable
ERROR:  relation "users" does not exist

Undefined table could mean I did not migrate

undefiend users means I mixed up singular and plural declaration

**Comment by JordanDickow** [comment]
file path for potential solution:
001-ba04-8dc874bffcdb] app/controllers/users_controller.rb:8:in `signup'

**Comment by JordanDickow** [comment]
For 500 error I ran  Heroku  run rails db:migrate - could solve 500 error
RESULTS:
== 1 CreateUsers: migrated (0.0290s) ==========================================

  ActiveRecord::SchemaMigration Create (1.4ms)  INSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"  [["version", "1"]]
   (1.5m
ActiveRecord::SchemaMigration Create (1.4ms)  INSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"  [["version", "1"]]
