### ISSUE TITLE
Clear Forms after data has been passed through it

### ISSUE THREAD

**Issue by JordanDickow** [JordanDickow/pokedex-project-2#4]

**Comment by JordanDickow** [comment]
Right now forms have a reset button but need - I need forms to clear with same button.

**Comment by JordanDickow** [comment]
I have a input tag to make a button but need to use a different method. 
HTML function isn't right.

**Comment by JordanDickow** [comment]
I used a jquery function
`$().trigger('reset)`
Successful Behavior

**Comment by JordanDickow** [comment]
onUpdateFailure forms does not clear

**Comment by JordanDickow** [comment]
I tried the .reset() jquery event with a failure result 
```
jquery.js:3841 jQuery.Deferred exception: "#update-pokemon".reset is not a function TypeError: "#update-pokemon".reset is not a function
    at Object.onUpdatePokemonFailure (http://localhost:7165/public/application.js:17293:21)
    at mightThrow (http://localhost:7165/public/vendor.js:12489:29)
    at process (http://localhost:7165/public/vendor.js:12557:12
```

**Comment by JordanDickow** [comment]
I targeted the `update-pokemon` id and still get undesired behavior with the same Jquery response

**Comment by JordanDickow** [comment]
Current code for onPokemonFailure
```
const onPokemonFailure = (responseData) {
$('#update-pokemon').trigger('reset')
$('message8').text('You do not have enough pokemon yet!').delay(800).hide('You do not have enough pokemon yet!')
console.log(responseData)
}
```

**Comment by JordanDickow** [comment]
What could I not be doing to have it not trigger a form clear

**Comment by JordanDickow** [comment]
The Update form still does not clear on failure response

**Comment by JordanDickow** [comment]
SideNote:
I targeted the messaging  to the `message7` class under `update-pokemon` id

**Comment by JordanDickow** [comment]
I changed the .then() promise from onUpdatePokemonFailure to ui.failure
I don't know why - really don't expect it to work. I have looked at all the updatePokemon files

**Comment by JordanDickow** [comment]
I purposely changed the targeted id and message class to check if I would get an appropriate response.

**Comment by JordanDickow** [comment]
I changed the jquery event to` $('#update-pokemon').reset('form')`

**Comment by JordanDickow** [comment]
THE ABOVE SOLUTION DID NOT WORK

**Comment by JordanDickow** [comment]
I changed .reset() to empty.

**Comment by JordanDickow** [comment]
The form does not reset but the jquery alert is gone - odd

**Comment by JordanDickow** [comment]
I passed form.id in my event file

**Comment by JordanDickow** [comment]
I'm checking the form workflow 
app.js > events.js > api.js > ui.js

**Comment by JordanDickow** [comment]
I wrote a script tag to load my app.js in my HTML?
<script src="js/app.js></script>

**Comment by JordanDickow** [comment]
I'm not getting any response from my onPokemonUpdateFailure. The event is  working with the right behavior but I need messaging to appear and the form to reset.

**Comment by JordanDickow** [comment]
I found an unnecessary  jquery event

**Comment by JordanDickow** [comment]
I NEED TO CHECK MY SYNTAX!!
 There was a missing $ in my jquery event
